### ISSUE TITLE
please remove dev trash from composer require section

### ISSUE THREAD

**Issue by alameya** [bigbluebutton/bigbluebutton-api-php#10]
like:
fabpot/php-cs-fixer
fzaninotto/faker
etc
it should be used in require-dev section

**Comment by GhaziTriki** [comment]
The pacakges you mention are useful for dev; far from being a trash; they are actually in ```require-dev``` and to avoid installing them please use ```composer install --no-dev```

Please check the composer.json again https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/composer.json#L29-L35

**Comment by alameya** [comment]
👍
