### ISSUE TITLE
Pre-upload multiple documents & keep the default whiteboard

### ISSUE THREAD

**Issue by Lukas2000** [bigbluebutton/bigbluebutton-api-php#108]
Does the API allow for multiple files to be uploaded when using the external call to load BIgBlueButton? 

Additionally, we noticed that when a file is selected for pre-uploading, the default whiteboard is no longer there among the file options. Is there a way to keep the default whiteboard as an option?

Thank you.

**Comment by GhaziTriki** [comment]
@Lukas2000 If you would like to pre-upload files it would replace the default presentation. In that case you should pre-upload your default presentation.
