### ISSUE TITLE
Create meeting with restricted viewers

### ISSUE THREAD

**Issue by vecdan** [bigbluebutton/bigbluebutton-api-php#109]
We are using BBB integrated into our own LMS and we are using PHP API. One of the used scenarios is "monitoring room" for student's distant exams (students runs on-line test, joined in the BBB room with webcam switched on and teachers monitors them). 
For this scenario, it will be very helpful, if there will be CreateMeetingParameter for locking viewers such as: See others viewers webcams,  Send Private chat messages, etc. Because teachers have to lock viewers manually for each monitoring room now and they forgot sometimes to do it.

Is it possible to add Lock viewers parameters to CreateMeeting API call, please? Or is there any other way how to do it now?

Thanks,  Daniel

**Comment by GhaziTriki** [comment]
Sure check the create API docs https://docs.bigbluebutton.org/dev/api.html#create
