### ISSUE TITLE
Unrealized api methods

### ISSUE THREAD

**Issue by toto4ds** [bigbluebutton/bigbluebutton-api-php#110]
Hi,
These methods are not implemented.
create:
    bannerText
    bannerColor
    allowModsToUnmuteUsers
    guestPolicy
join:
    defaultLayout
    guest

**Comment by sualko** [comment]
Hi @toto4ds, we created a fork with many enhancements and fixes. We also implemented most of those requested methods. Just checkout https://github.com/littleredbutton/bigbluebutton-api-php and if something is missing, just open an issue there.

**Comment by czange** [comment]
Is there any setting that allows to use the wait for moderator method?

**Comment by GhaziTriki** [comment]
@toto4ds & @czange Can you please check the dev branch?
