### ISSUE TITLE
Problem with Browser check on Devices WebView

### ISSUE THREAD

**Issue by mcferdev** [bigbluebutton/bigbluebutton-api-php#111]
I am trying to use a WebView on Android, but with all emulators[ I got a error saying there is a old version of the browser. But when I check the version is higher and updated.
How can I disable this check ?
Look like the same problem [here](https://github.com/bigbluebutton/bigbluebutton/issues/8152) , but I haven´t success changing the file /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml  like the user suggested.

**Comment by sualko** [comment]
How is this related to the php api?
