### ISSUE TITLE
how can limit online users in bigbluebutton

### ISSUE THREAD

**Issue by ashkan1627** [bigbluebutton/bigbluebutton-api-php#112]
Hi, everyone
I Use Learndash LMS in wordpress by bigblubutton plugin and I need to limit users online in bigbluebutton.
for example only 50 user can enter the class
how can i do it?

**Comment by jibon57** [comment]
I have sent a pull request here: https://github.com/blindsidenetworks/wordpress-plugin_bigbluebutton/pull/85 but don't know why maintainer didn't notice. You can try my version from here: https://github.com/jibon57/wordpress-plugin_bigbluebutton
