### ISSUE TITLE
Create new tagged release

### ISSUE THREAD

**Issue by botris** [bigbluebutton/bigbluebutton-api-php#116]
~~Even though the `muteOnStart` method is implemented, the setting is not respected. This is due to the fact that the boolean is not transformed to a true / false string in the `getHTTPQuery` method.
As the tests only validate the methods and the properties and not the `getHTTPQuery` method this is not caught.~~

--edit--
It seems the original issue is actually fixed but no tagged version was released since, so it's not retrieved by composer.

**Comment by GhaziTriki** [comment]
@botris Do you mean it is in the master but not tagged?

**Comment by botris** [comment]
@GhaziTriki yes therefor composer won't pull in the new changes.

**Comment by sualko** [comment]
Hi botris :wave:. You can also use [our fork](https://github.com/littleredbutton/bigbluebutton-api-php) to get an modern up-to-date API for BBB and the best thing is that this fix is already included :tada:.
