### ISSUE TITLE
How to manage configs

### ISSUE THREAD

**Issue by voltan** [bigbluebutton/bigbluebutton-api-php#117]
Hello

I use bigbluebutton-api-php on my application to make a meeting room. My application manage online events and I want event owner can do make some configs like disable camera and microption for all people and same

Can I set some options like this by php api ? how I can do it? 

thank you so much

**Comment by sualko** [comment]
Hi,

you have to check the [BBB API](https://docs.bigbluebutton.org/dev/api.html) if such an config is possible. For example during the room creation you can set webcamsOnlyForModerator to true. Afterwards you can set the parameter through this API. Usually something like `$creationParams->setWebcamsOnlyForModerator(true);`.
