### ISSUE TITLE
Use strlen instead of mb_strlen

### ISSUE THREAD

**Issue by Ezanor** [bigbluebutton/bigbluebutton-api-php#118]
Hi,

Is there any reason to use  mb_strlen instead of strlen for the Content-Length header here :
https://github.com/bigbluebutton/bigbluebutton-api-php/blob/48aa35340213fd3a6f3d6d81eb54d7b4eebef141/src/BigBlueButton.php#L475

mb_strlen get number of char VS strlen get the number of octets.

I just found that pre-uploading multiple pdf with some char cause bbb-web to stop reading body before the closing tag  of the module presentation. And  the create request fail.

**Comment by GhaziTriki** [comment]
@Ezanor Can you please provide more information?

**Comment by GhaziTriki** [comment]
More info here https://www.rfc-editor.org/rfc/rfc9110.html#section-8.6

**Comment by GhaziTriki** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton-api-php/commit/3fcfbd6e7a29d49b763405c6cdfd4918dd80bfc7

**Comment by DigitalTimK** [comment]
Commit https://github.com/bigbluebutton/bigbluebutton-api-php/commit/3fcfbd6e7a29d49b763405c6cdfd4918dd80bfc7 not solving issue. `cs-fixer`is reverting `strlen()` back to `mb_strlen()`
