### ISSUE TITLE
API url without bigbluebutton

### ISSUE THREAD

**Issue by createoppurtuinities** [bigbluebutton/bigbluebutton-api-php#119]
Dear Experts,

Can we have the api url generated without bigbluebutton like with only

i want the API url without bigbluebutton in the url. is it possible?
normal url looks like below
http://<your_hostname>/bigbluebutton/api/isMeetingRunning?meetingID=abcdef

But the api url which i provide to my partner application should be like below

http://<your_hostname>/api/isMeetingRunning?meetingID=abcdef

can someone give me some insights on the same

**Comment by esfahanweb** [comment]
@createoppurtuinities 

I think it does not belong to this package's functionality.
these endpoints are defined in the BBB server and this is just a PHP wrapper to work with that.
you can use your own endpoints if you want to hide them from the end-user.

**Comment by createoppurtuinities** [comment]
I am pretty new in this. can you please let me know how i can define my own
end points. your help is greatly appreciated

**Comment by esfahanweb** [comment]
> I am pretty new in this. can you please let me know how i can define my own end points. your help is greatly appreciated

you're welcome,
are you familiar with rest API in PHP?
ie. you can create an URL such as `http://<your_domain>/api/isMeetingRunning?meetingID=abcdef` and use BBB API in background when this URL requested by user.
actually you should use BBB API to communicate your backend with BBB server and show your own URLs to end-user. (for security reason)

**Comment by createoppurtuinities** [comment]
Ohh great, thanks a lot for letting me know this. How to connect these APIs
togather.

Can we use these php rest APIs to any application?

Currently the requirement is  one of our partner is asking for api to use
it in their application where they serve it to their customers on their
brand.

What is the way to share the APIs now.

Can you kindly give me some clarity on this?

**Comment by esfahanweb** [comment]
the BBB server has several API endpoints and these APIs are not belong to this package.

more information can be found here:
`https://mconf.github.io/api-mate/`

if you want to create your application with PHP, you can use this package to communicate with BBB APIs.

you can give the BBB APIs and your secret to your partner and they have to develop their application.

**Comment by createoppurtuinities** [comment]
Is it safe to provide our secret to our partner? Is this the only way or do
we have any other option?

Can we also do this with java api like providing api with our own domain
api instead of using bigbluebutton in the api url?

Like https://mydomain.com/api

**Comment by esfahanweb** [comment]
NO, it's not safe!
with the secret key, they can access to all your BBB server meetings!

if you have a BBB server and you want to share meetings with others, you have to create your own API and give them access to that with your preferred access controls.

you can look at `https://mconf.github.io/api-mate/` and create your own APIs in any language(java, js, ruby, python, ...) and this package just make it easier for PHP.

**Comment by createoppurtuinities** [comment]
Ohh great, thank you so much.

One more thing I want know is if my partner have an application devveloped
in java or any lms platform like Moodle will I be able to provide him with
php api?

Will it be compatible?

In java api can we provide our own api with my own domain with
bigbluebutton like

https://mydomain.com/api

Instead of

https://mydomain.com/bigbluebutton/api

**Comment by esfahanweb** [comment]
It absolutely belongs to the developed app or the moodle's plugin to compatible with your APIs, otherwise, you have to create your APIs completely similar to BBB APIs.

**Comment by createoppurtuinities** [comment]
If not compatible then URLs to similar to BBB means similar like this?

https://mydomain.com/bigbluebutton/api/fghjhffdgyyjjbgcxc

Then we also need to share the screte as well?

**Comment by esfahanweb** [comment]
Yes,
the common plugins or applications designed to work with BBB APIs, if you change your endpoints, you have to change that plugin or application too.

**Comment by andrekutianski** [comment]
maybe this can be related to #165 ?
