### ISSUE TITLE
The Bigbluebutton running with flash, How I can change to HTML5

### ISSUE THREAD

**Issue by mahmoudabdelhalim** [bigbluebutton/bigbluebutton-api-php#121]

**Comment by sualko** [comment]
Hi @mahmoudabdelhalim,

you probably need to configure your bbb instance to only use html5, or set the `joinViaHTML5` parameter during the join call. See https://docs.bigbluebutton.org/dev/api.html#join.

**Comment by GhaziTriki** [comment]
Thank you @sualko for pointing to the right docs.
