### ISSUE TITLE
Fatal error: Class 'BigBlueButton\TestCase' not found

### ISSUE THREAD

**Issue by mojtabahub** [bigbluebutton/bigbluebutton-api-php#122]
Hello, 
thanks for awesome software

I am extremely new to use Big Blue Button API

I want use your example php in windows. I am not sure I am in right way or not. please guidance me if I am not in right way

I Installed your example with `composer require bigbluebutton/bigbluebutton-api-php:~2.0.0` command as you said in wiki

also my curl version installed is `curl 7.55.1` and i checked `mbstring`, it included in xampp php.ini file too. 

i try to run BigBlueButtonTest.php file i got this error:
`Fatal error: Class 'BigBlueButton\TestCase' not found in D:\Projects\Programming\API\BBB\vendor\bigbluebutton\bigbluebutton-api-php\tests\BigBlueButtonTest.php on line 38`

why that happened? is it because there is need some Xampp config? is there need to config `BBB_SECRET` and `BBB_SERVER_BASE_URL` on Xampp? How can do that?

Thank you so much

**Comment by sualko** [comment]
Hi @mojtabahub, 

you maybe like to test [our fork](https://github.com/littleredbutton/bigbluebutton-api-php), because we fixed those test cases and added a lot of other improvements. Have fun!

**Comment by GhaziTriki** [comment]
Unit test have been fixed in the latest release.
