### ISSUE TITLE
Use just the API without Website

### ISSUE THREAD

**Issue by mcferdev** [bigbluebutton/bigbluebutton-api-php#123]
Hi, 

If I remove GreenLight and the BigBlueButton HomePage (/var/www/bigbluebutton-default/index.html), it´s enough to use the BBB (concerning about security) ?
Because I have created a App to use and on the beginning we don´t want any website.

**Comment by spyp** [comment]
Yes you can
Greenlight is like simple website that wrapper api
dont use greenlight at all and remove it

**Comment by mcferdev** [comment]
> Yes you can
> Greenlight is like simple website that wrapper api
> dont use greenlight at all and remove it

But it´s enough deleting it and removing index.html webpage ? .
