### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by maxgilcosta** [bigbluebutton/bigbluebutton-api-php#127]
Hi, a little observation:
In APP docs => create, the param "welcome" dont work in PHP API. 
I use "WelcomeMessage" and works fine.

**Comment by maxgilcosta** [comment]
I use "WelcomeMessage" and works fine. 
$createMeetingParams->setWelcomeMessage("Welcome message");

**Comment by joisarjignesh** [comment]
@maxgilcosta  used param "welcomeMessage" not "welcome"
