### ISSUE TITLE
GetMeetingInfo doesn't require a moderator password

### ISSUE THREAD

**Issue by SamuelWei** [bigbluebutton/bigbluebutton-api-php#130]
The docs and the source code only requires the meeting and and not the moderator password for the getmeetinginfo api: https://docs.bigbluebutton.org/dev/api.html#getmeetinginfo

That makes sence, because you could read the same data with the getMeetings API that can't require a moderator password by design.

Is there any reason to keep the password parameter in the GetMeetingInfoParameters class?
You might also want to update https://mconf.github.io/api-mate/ as it is also using the moderator password

**Comment by GhaziTriki** [comment]
@SamuelWei I think it is an old requirement that have been changed since. I have to double-check.
