### ISSUE TITLE
Moodle high load because of api loading records

### ISSUE THREAD

**Issue by hamedunik** [bigbluebutton/bigbluebutton-api-php#133]
My LMS Moodle cpu usage will go high upon starting bigbluebutton meetings. It seems when I have near 800 users and using scalelite and bigbluebutton API, the time to seek for and load of recording of each recorded presentation is too much and it will affect performance of LMS. Teachers should wait long time to see JOIN MEETING. how is it possible to reduce time? is it possible to just call the recorded name and date to reduce time?

**Comment by GhaziTriki** [comment]
Dear @hamedunik, thank you for filing the issue. But I don't see how it is related to the API library?
