### ISSUE TITLE
Wrong license in composer.json

### ISSUE THREAD

**Issue by KimBrodowski** [bigbluebutton/bigbluebutton-api-php#134]
Hello,

the composer.json states this project is licensed under GPL while the LICENSE file states the project is released under LGPL.

This is a problem, since as a commercial proprietary software vendor we cannot use GPL licensed code except under very specific circumstances.

https://github.com/bigbluebutton/bigbluebutton-api-php/blob/1c8fb609e901c4932609608a5ab98a1c31115d63/composer.json#L11

https://github.com/bigbluebutton/bigbluebutton-api-php/blob/1c8fb609e901c4932609608a5ab98a1c31115d63/LICENSE#L1

Please correct this mistake.

Best regards,
Kim-Alexander Brodowski

**Comment by GhaziTriki** [comment]
Thanks @KimBrodowski it will be fixed.

**Comment by GhaziTriki** [comment]
License fixed https://github.com/bigbluebutton/bigbluebutton-api-php/commit/82b30feb01584b53c98364ae7988247b94bbbf5c
