### ISSUE TITLE
How Can I access the recordings and Meetings done through the API ?

### ISSUE THREAD

**Issue by mcferdev** [bigbluebutton/bigbluebutton-api-php#135]
I have the Greenlight "version" and now I have done my App, that uses the bbb API, but I would like to get all the meetings created by a user, because they´re the same (LDAP users).
How Can I access the recordings and Meetings done through the API and the Greenlight? I can´t see both together
Which parameters the Greenlight uses to get them?

**Comment by GhaziTriki** [comment]
If you want to access all the meetings created via Greenlight please search with metadata `bbb-origin` equals to `Greenlight`.
