### ISSUE TITLE
getRecordings API

### ISSUE THREAD

**Issue by szekster** [bigbluebutton/bigbluebutton-api-php#138]
I can successfully call getRecordings() and fetch an object that contains all the data for all recordings.  My issue is that there does not seem to be any methods for which to access the individual records in the returned object.  getMessage,  getRawXml seem to return empty data or arrays.  I ended up making a modification such that getRecordings returns just XML, then I convert that XML to an associative array and can access the data that way.  So instead of modifying the code I would have to extend the class to create a new method to return just XML, which is Ok, but I am wondering if I am just missing something obvious.

If there is a solution without modifying the class could someone please post examples, here's tha basics of what I have done:

$bbb = new BigBlueButton();
		try {
			$client=$bbb->getRecordings(new GetRecordingsParameters() ); 
		} catch (Exception $e) {
			$errstr=$e->getMessage();
			$errno=$e->getCode();
			$client=false;
		}
		if ($client && $client->success() ) {
                        print_r($client,1);  //this shows that the object contains all the needed data.
			error_log("RAW XML: ".$client->getRawXml() ); //returns empty array
			error_log("Get Message: ".$client->getMessage() ); //returns no data
                 }

**Comment by cahueya** [comment]
This is what I did:
            if ($response->getReturnCode() == 'SUCCESS') {
                foreach ($response->getRawXml()->recordings->recording as $recording) {
                    $recordingurl = $recording->playback->format->url;

**Comment by szekster** [comment]
awesome, yes, this works.. thank you!
