### ISSUE TITLE
Multiple declarations of setFreeJoin() function in CreateMeetingParameters file

### ISSUE THREAD

**Issue by tecziq** [bigbluebutton/bigbluebutton-api-php#141]
There are multiple declarations of setFreeJoin() function in CreateMeetingParameters file.

What i did for installation is :- composer require bigbluebutton/bigbluebutton-api-php:~2.0.0

![image](https://user-images.githubusercontent.com/19544454/114829729-10385480-9de9-11eb-8976-140ea8a1e6cf.png)
![image](https://user-images.githubusercontent.com/19544454/114829671-ff87de80-9de8-11eb-8b2a-0f34c32c60f1.png)

**Comment by GhaziTriki** [comment]
Fixed.
