### ISSUE TITLE
Error: "Warning: SimpleXMLElement::__construct():" 

### ISSUE THREAD

**Issue by diable2010** [bigbluebutton/bigbluebutton-api-php#143]
**PHP:**

`<?php

require 'vendor/autoload.php';
	
use BigBlueButton\BigBlueButton;
use BigBlueButton\Core\ApiMethod;
use BigBlueButton\Exceptions\BadResponseException;
use BigBlueButton\Parameters\CreateMeetingParameters;
use BigBlueButton\Parameters\DeleteRecordingsParameters;
use BigBlueButton\Parameters\EndMeetingParameters;
use BigBlueButton\Parameters\GetMeetingInfoParameters;
use BigBlueButton\Parameters\GetRecordingsParameters;
use BigBlueButton\Parameters\HooksCreateParameters;
use BigBlueButton\Parameters\HooksDestroyParameters;
use BigBlueButton\Parameters\IsMeetingRunningParameters;
use BigBlueButton\Parameters\JoinMeetingParameters;
use BigBlueButton\Parameters\PublishRecordingsParameters;
use BigBlueButton\Parameters\UpdateRecordingsParameters;
use BigBlueButton\Parameters\SetConfigXMLParameters;
use BigBlueButton\Responses\ApiVersionResponse;
use BigBlueButton\Responses\CreateMeetingResponse;
use BigBlueButton\Responses\DeleteRecordingsResponse;
use BigBlueButton\Responses\EndMeetingResponse;
use BigBlueButton\Responses\GetDefaultConfigXMLResponse;
use BigBlueButton\Responses\GetMeetingInfoResponse;
use BigBlueButton\Responses\GetMeetingsResponse;
use BigBlueButton\Responses\GetRecordingsResponse;
use BigBlueButton\Responses\HooksCreateResponse;
use BigBlueButton\Responses\HooksDestroyResponse;
use BigBlueButton\Responses\HooksListResponse;
use BigBlueButton\Responses\IsMeetingRunningResponse;
use BigBlueButton\Responses\JoinMeetingResponse;
use BigBlueButton\Responses\PublishRecordingsResponse;
use BigBlueButton\Responses\SetConfigXMLResponse;
use BigBlueButton\Responses\UpdateRecordingsResponse;
use BigBlueButton\Util\UrlBuilder;

$bbb                 = new BigBlueButton();
$createMeetingParams = new CreateMeetingParameters('adm-ccf-e4j-774', 'BigBlueButton API Meeting');
$createMeetingParams = $createMeetingParams	->setModeratorPassword('123456')
											->setAttendeePassword('000000');
$bbb->createMeeting($createMeetingParams);

$joinMeetingParams = new JoinMeetingParameters('adm-ccf-e4j-999', 'user', '123456');
$joinMeetingParams->setRedirect(false);

$joinResponse = $bbb->joinMeeting($joinMeetingParams);`

**Error:**

`
PHP Warning:  SimpleXMLElement::__construct(): Entity: line 36: parser error : Opening and ending tag mismatch: meta line 12 and head in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 495
PHP Warning:  SimpleXMLElement::__construct():   &lt;/head&gt; in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 495
PHP Warning:  SimpleXMLElement::__construct():          ^ in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 495
PHP Warning:  SimpleXMLElement::__construct(): Entity: line 129: parser error : Opening and ending tag mismatch: head line 4 and html in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 495
PHP Warning:  SimpleXMLElement::__construct(): &lt;/html&gt; in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 495
PHP Warning:  SimpleXMLElement::__construct():        ^ in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 495
PHP Warning:  SimpleXMLElement::__construct(): Entity: line 130: parser error : Premature end of data in tag html line 3 in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 495
PHP Warning:  SimpleXMLElement::__construct():  in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 495
PHP Warning:  SimpleXMLElement::__construct(): ^ in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 495
PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:495
Stack trace:
#0 /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(495): SimpleXMLElement->__construct('\n<!DOCTYPE html...')
#1 /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(173): BigBlueButton\BigBlueButton->processXmlResponse('https://liveser...')
#2 /home/.../test.php(57): BigBlueButton\BigBlueButton->joinMeeting(Object(BigBlueButton\Parameters\JoinMeetingParameters))
#3 {main}
  thrown in /home/.../vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 495
`

What is the reason?
Thank you.

**Comment by GhaziTriki** [comment]
@diable2010 It looks your API is not responding.
