### ISSUE TITLE
bannerText and bannerColor missing

### ISSUE THREAD

**Issue by wb7** [bigbluebutton/bigbluebutton-api-php#144]
Hello,

the mentioned fields in the API docs (https://docs.bigbluebutton.org/dev/api.html) "bannerText" and "bannerColor" in the create method cannot be set using the PHP API.

Is there a reason for this?

Thanks in advance,
wb7

**Comment by GhaziTriki** [comment]
@wb7 Can you please test the dev branch?

**Comment by GhaziTriki** [comment]
Implemented in https://github.com/bigbluebutton/bigbluebutton-api-php/releases/tag/2.1.0
