### ISSUE TITLE
How to update a meeting after creation with API

### ISSUE THREAD

**Issue by czange** [bigbluebutton/bigbluebutton-api-php#145]
What is the way to update meeting room settings once the meeting room was created - like it is possible in green light?

e.g. changing welcome message etc.

**Comment by ffdixon** [comment]
It's not possible as the meeting parameters have been set.   For example, if you create a meeting with `moderatorPW=abc` and then send the same `create` API call and change `moderatorPW=abcd`, the meeting will have the initial password.

**Comment by czange** [comment]
Hi Fred, thanks for this reply - but how can you change room settings in greenlight? It is clear that, if the room is actively running, there is no change in settings - but for the next meeting it works. In green light you always can adapt settings, like password etc.

**Comment by czange** [comment]
@ffdixon Sorry for asking again. It is for the BBB Module that we implemented for Drupal - so we need this information to be able to finalise some of the features. What I observed is, that you can create rooms in GREENLIGHT and you also can change settings for this rooms anytime (e.g. the password). 

How is that working - you obviously only create the room once the meeting starts, right? But how do you keep recordings and everything together for the room?
