### ISSUE TITLE
API Call GetMeetingInfo

### ISSUE THREAD

**Issue by globenewmedialtd** [bigbluebutton/bigbluebutton-api-php#146]
Why is there an additional parameter used, when the original API Call does not need a moderator pw?
https://docs.bigbluebutton.org/dev/api.html#getmeetinginfo

**Comment by GhaziTriki** [comment]
Updated in https://github.com/bigbluebutton/bigbluebutton-api-php/commit/5912586b182a2919d7ddbc712489d9d3d728bd4f
