### ISSUE TITLE
Missing few parameters in GetRecordings response

### ISSUE THREAD

**Issue by omsrivastava** [bigbluebutton/bigbluebutton-api-php#147]
The following parameters are required but these are missing in **Record** class under **BigBlueButton\Core** namespace -
1. size
2. preview
    a. images

**Comment by GhaziTriki** [comment]
Formats should be an array too.

**Comment by GhaziTriki** [comment]
@omsrivastava Thanks for spotting it. It is now implemented `$record->images()`
