### ISSUE TITLE
How to configure a Wait for Moderator Setting

### ISSUE THREAD

**Issue by czange** [bigbluebutton/bigbluebutton-api-php#150]
How to configure a **wait for moderator** setting through the API. I know about the guest_policy - but I assume this is a different api setting. We need this for the development of the drupal client.

**Comment by pedrobmarin** [comment]
https://docs.bigbluebutton.org/dev/api.html#create

Search for `guestPolicy`. If you are using a third party API wrapper (php, javascript, ruby...), make sure to check it's documentation on it.

**Comment by czange** [comment]
Thanks Pedro, I know about Guest Policy - the values are always allow, always deny and approve by moderator. But I am looking for the value "wait for moderator" which means viewers have to wait for the moderator to login - and will then be polled into the meeting automatically.

**Comment by czange** [comment]
guest policy has a problem with our PHP API Version - but I think it is a different thing anyways

**Comment by pedrobmarin** [comment]
Yeah... I remember seeing some folks asking similar questions over here. Maybe check on these guys improvements over this api https://github.com/bigbluebutton/bigbluebutton-api-php/issues/110

**Comment by czange** [comment]
Well - not really, thanks anyway.

I am looking for a specific setting, different from ASK_Moderator - which is Wait for Moderator - so people can only join in, once the moderator is there.

**Comment by pedrobmarin** [comment]
As far as I know, and I'm one of the developers of this guest thing, there's no such thing you are asking besides the guestPolicy=ASK_MODERATOR.

**Comment by pedrobmarin** [comment]
Maybe this is something greenlight does outside the bigbluebutton server and it's causing the confusion...

**Comment by czange** [comment]
Hi Pedro - this setting is available in Greenlight. How do they do it? this is the setting I am looking for. It is per default on YES in our BBB implementation for Drupal (which we are developing, and are going to share as open source with the world ASAP)
<img width="1443" alt="2021-08-23_21-37-56" src="https://user-images.githubusercontent.com/61565801/130508812-4f409cb8-5a76-46b4-8d4d-1eca3be3b7b5.png">

**Comment by czange** [comment]
I need this setting to be manageable - or to be default on No - which is better

**Comment by pedrobmarin** [comment]
I'm afraid you'll have to check with the greenlight developers https://github.com/bigbluebutton/greenlight. I'm not aware of the details...

**Comment by czange** [comment]
Thanks Pedro this helps a lot - and I think I understand now, how that works - it works totally through the client.... So if that is the case, we also can do this - as we can check if there is a moderator....
