### ISSUE TITLE
Using getMeetingInfo to get current BBB-SERVER-URL

### ISSUE THREAD

**Issue by michaelchen001** [bigbluebutton/bigbluebutton-api-php#151]
Hi,all
I am using scalelite for BBB load balancer.  The getMeetingInfo API will return all of a meeting’s information. but I also want to know which BBB server supporting this meeting.

Can it return below info?
 `<meetingServer>https://example1.com</meetingServer>`

`
<response>
  <returncode>SUCCESS</returncode>
  **<meetingServer>https://example1.com</meetingServer>**
  <meetingName>Demo Meeting</meetingName>
  <meetingID>Demo Meeting</meetingID>
……
<response>
`

**Comment by GhaziTriki** [comment]
@michaelchen001 This is a request for scalelite. With the API you can access the XML raw data and display it.
