### ISSUE TITLE
add endWhenNoModerator and endWhenNoModeratorDelayInMinutes

### ISSUE THREAD

**Issue by kaystrobach** [bigbluebutton/bigbluebutton-api-php#153]
https://docs.bigbluebutton.org/dev/api.html#create

adds some more parameters to the uri. Please add the following 2 paramters to the 

* endWhenNoModerator
* endWhenNoModeratorDelayInMinutes

**Comment by GhaziTriki** [comment]
Thanks @kaystrobach will be done as soon as possible.

**Comment by kaystrobach** [comment]
Thank you.

**Comment by kaystrobach** [comment]
If needed, i can also check for the other arguments.

**Comment by kaystrobach** [comment]
will you accept a PR on this?

**Comment by GhaziTriki** [comment]
@kaystrobach Can you please check the dev branch?

**Comment by kaystrobach** [comment]
pinned it for next week. thank you

**Comment by kaystrobach** [comment]
Works ™️ - thank you

**Comment by GhaziTriki** [comment]
Thank you @kaystrobach
