### ISSUE TITLE
update meta  of recording files

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton-api-php#155]
Hi, Why this excellent package does not provide https://docs.bigbluebutton.org/dev/api.html#updaterecordings functions?
I want to update meta data of recording. Could you help me?

**Comment by GhaziTriki** [comment]
Hi @cod3r0k,

It does, check here https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/src/BigBlueButton.php#L359

**Comment by cod3r0k** [comment]
Thanks @GhaziTriki
