### ISSUE TITLE
404 error on /bigbluebutton/api/create

### ISSUE THREAD

**Issue by Entretoize** [bigbluebutton/bigbluebutton-api-php#159]
Everything was working, but after a certicate expiration, I had to update bbb and ubuntu and now nothing works, when I try to start a conference I receive that errors:

`Fatal error: Uncaught BigBlueButton\Exceptions\BadResponseException: Bad response, https://mydomain/bigbluebutton/api/create?name=confname&meetingID=confid&attendeePW=123456&moderatorPW=123456&logoutURL=https%3A%2F%2Fmydomain&record=false&duration=3600&autoStartRecording=false&allowStartStopRecording=false&welcome=somemessage&webcamsOnlyForModerator=false&muteOnStart=false&guestPolicy=ALWAYS_ACCEPT&lockSettingsDisableCam=false&lockSettingsDisableMic=false&lockSettingsDisablePrivateChat=false&lockSettingsDisablePublicChat=false&lockSettingsDisableNote=false&lockSettingsHideUserList=false&lockSettingsLockedLayout=false&lockSettingsLockOnJoin=true&lockSettingsLockOnJoinConfigurable=false&allowModsToUnmuteUsers=false&checksum=2c696d2b524961987fe2b770d086b35a174caaa2 HTTP code: 404 in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:491 Stack trace: #0 /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(115): BigBlue in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 491`

I updated to 2.0.13 with no success, I don't understand what to do.

**Comment by GhaziTriki** [comment]
@Entretoize Is your server endpoint reachable? It looks not.
