### ISSUE TITLE
Since 2.4 meetingLayout exist

### ISSUE THREAD

**Issue by fran6t** [bigbluebutton/bigbluebutton-api-php#160]
Since 2.4 api authorize at creating meeting parameter meetingLayout with possible values CUSTOM_LAYOUT, SMART_LAYOUT, PRESENTATION_FOCUS, VIDEO_FOCUS 

I have try in my code php
$create->meetingLayout('VIDEO_FOCUS');

At execution i have error 
Fatal error: Uncaught Error: Call to undefined methos BigBlueButton\Parameters\CreateMeetingParameters::meetingLayout()

Is my code wrong ? If not, is anybody who add this to api-php ?

**Comment by GhaziTriki** [comment]
@fran6t Can you please test the `dev` branch and let us know if it works?

**Comment by GhaziTriki** [comment]
Implemented in https://github.com/bigbluebutton/bigbluebutton-api-php/releases/tag/2.1.0
