### ISSUE TITLE
Unhandled curl error: Could not resolve host: api 

### ISSUE THREAD

**Issue by TysonOsore** [bigbluebutton/bigbluebutton-api-php#161]
Fatal error: Uncaught RuntimeException: Unhandled curl error: Couldn't resolve host 'api' in /Applications/XAMPP/xamppfiles/htdocs/stream/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:487 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/stream/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(115): BigBlueButton\BigBlueButton->processXmlResponse('api/create?name...', '') #1 /Applications/XAMPP/xamppfiles/htdocs/stream/index.php(29): BigBlueButton\BigBlueButton->createMeeting(Object(BigBlueButton\Parameters\CreateMeetingParameters)) #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/stream/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 487

**Comment by baumkirchner** [comment]
You need to set your BBB-servers **URL** and your BBB-servers **Secret** as _environment variables_ first.
`sudo bbb-conf --secret` on your BBB-server will display them for you.
[This discussion](https://stackoverflow.com/questions/8098927/nginx-variables-similar-to-setenv-in-apache) may help in setting them on your web server
