### ISSUE TITLE
API password is deprecated, phased out in 2.6 of BBB

### ISSUE THREAD

**Issue by peinwag** [bigbluebutton/bigbluebutton-api-php#177]
According to bigbluebutton/bigbluebutton#14962 the `attendeePW` and `moderatorPW`are being deprecated / phased out in 2.6 and are optional as of 2.4. 

As this is somehow a breaking change at least for 2.6 it should be considered.

**Comment by GhaziTriki** [comment]
Hi @peinwag 

We have updated the library to accept the password or the role and kept backward compatibility here https://github.com/bigbluebutton/bigbluebutton-api-php/commit/a100bbcebdfd1756d483aa822df0bdc89c5841e8
