### ISSUE TITLE
Is there anyway to get the total size of the a meeting recording?

### ISSUE THREAD

**Issue by tamkeen-tms** [bigbluebutton/bigbluebutton-api-php#178]
I am looking for a way to fetch or calculate the file size of a meeting's recording. I have looked into the /[getRecordings ](https://docs.bigbluebutton.org/dev/api.html#getrecordings)endpoint, but nothing there about storage or size.

**Comment by tamkeen-tms** [comment]
Looking at the BBB repo, I found this pull request from 2018:
https://github.com/bigbluebutton/bigbluebutton/pull/6351

There are 3 "size" values, all in bytes. The first "size" is the total size of the recording directory, the "rawSize" is the size of the raw recording file. The final "size" value is a property for each playback item.

These values are not accessible through the \Core\Record class. I have created an extending class and add ->getSize() as a work around.

**Comment by GhaziTriki** [comment]
@tamkeen-tms You can get the size of all recording formats.
