### ISSUE TITLE
When the API URL is incorrect that will lead to an uncaught PHP Exception

### ISSUE THREAD

**Issue by globenewmedia** [bigbluebutton/bigbluebutton-api-php#183]
BigBlueButton\Exceptions\BadResponseException: Bad response, HTTP code: 404 in BigBlueButton\BigBlueButton->processXmlResponse() (line 485 of /var/www/example/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php).

```
            $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            if ($httpcode < 200 || $httpcode >= 300) {
                throw new BadResponseException('Bad response, HTTP code: ' . $httpcode);
            }
```

PHP message: Uncaught PHP Exception BigBlueButton\Exceptions\BadResponseException

**Comment by xJuvi** [comment]
hi there,
that's no bug. You must catch the "BadResponseException" in your code. If you doesn't catch the exception, it's an uncaught exception. That is the error.

Kind regards.

**Comment by GhaziTriki** [comment]
This Exception should be handled in the integration using the library.
