### ISSUE TITLE
Push new api version for BBB 2.6 to packagist

### ISSUE THREAD

**Issue by xJuvi** [bigbluebutton/bigbluebutton-api-php#192]
Hey there,
we use this api via composer. So BBB 2.6 will be soon released and we need to update the api to create and join meeting via role instead of passwords.

Can you push a new version of this repo to packagist?

Kind regards

**Comment by xJuvi** [comment]
@GhaziTriki any feedback for me?

**Comment by GhaziTriki** [comment]
I think role based is already in the dev-master I think.

**Comment by xJuvi** [comment]
Thanks. It's ok so.
