### ISSUE TITLE
new Release?

### ISSUE THREAD

**Issue by SandraLin1** [bigbluebutton/bigbluebutton-api-php#195]
Hi,
will there be a new release with all the missing features and new functions anytime soon?
Thanks a lot

**Comment by xJuvi** [comment]
Hi @SandraLin1 
you can change to the dev-master Branch in your Composer file. There you will get the latest commits before a new release is ready. 

Kind regards

**Comment by GhaziTriki** [comment]
Hi @SandraLin1 
Yes we are working on a new release. What features are missing?

**Comment by GhaziTriki** [comment]
@SandraLin1 We are preparing a new release here

https://github.com/bigbluebutton/bigbluebutton-api-php/releases/tag/untagged-1a52470d2af17a00e94d

**Comment by GhaziTriki** [comment]
2.2.0 released https://github.com/bigbluebutton/bigbluebutton-api-php/releases/tag/2.2.0
