### ISSUE TITLE
Upload presentation not working.Can you help me achieve uploading a presentation?

### ISSUE THREAD

**Issue by YouAreALegend** [bigbluebutton/bigbluebutton-api-php#199]
I tried the following two methods to upload a presentation.
1.
$createMeetingParams = new CreateMeetingParameters($meeting_id, $meeting_name);
$createMeetingParams->setPreUploadedPresentationOverrideDefault(TRUE);
$createMeetingParams->addPresentation($nameOrUrl,$content);
$bbb->createMeeting($createMeetingParams);

Get:RuntimeException：BigBlueButton\BigBlueButton->sendRequest() Unhandled curl error: Empty reply from server
2.
$insertDocumentParameters = new InsertDocumentParameters($meeting_id);
$insertDocumentParameters->addPresentation($nameOrUrl,$content);
$bbb->insertDocument($insertDocumentParameters->getPresentationsAsXML());
Still not working.
Except for uploading the presentation, everything else is running normally.

**Comment by GhaziTriki** [comment]
Hi @YouAreALegend 

I never tried "setPreUploadedPresentationOverrideDefault". Can you try without that option?

**Comment by YouAreALegend** [comment]
I removed setPreUploadedPresentationOverrideDefault and still reported an error:
RuntimeException: Unhandled curl error: Empty reply from server in BigBlueButton\BigBlueButton->sendRequest() (line 583 of /www/wwwroot/lms/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php).

**Comment by MindScientist** [comment]
I have the same issue. Tried to add a presentation by the first way calling
`$createMeetingParams->addPresentation($nameOrUrl, $content);`
I don't receive error message but when I join a meeting by link, I see no presentation.

**Comment by andrekutianski** [comment]
What is your BBB and library versions?

**Comment by YouAreALegend** [comment]
2.6

**Comment by YouAreALegend** [comment]
Upgrade BBB to 2.6.9
createMeetingParams->addPresentation($nameOrUrl);
Still not working.
**Error report content:**RuntimeException: Unhandled curl error: Empty reply from server in BigBlueButton\BigBlueButton->sendRequest() (line 594 of /www/wwwroot/lms/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php).

**Comment by YouAreALegend** [comment]
> 我有同样的问题。 尝试通过第一种调用方式添加演示文稿 `$createMeetingParams->addPresentation($nameOrUrl, $content);` 我没有收到错误消息，但当我通过链接加入会议时，我看不到任何演示文稿。

Have you resolved the issue of not being able to upload the presentation?

**Comment by YouAreALegend** [comment]
I've updated to the latest dev-master.And a bit confused. If I want to upload a presentation, should I use the CreateMeetingParameters object or the InsertDocumentParameters object?
If I use the addPresentation method of CreateMeetingParameters to upload a presentation, will still report an error.Which was:
RuntimeException: Unhandled curl error: Empty reply from server in BigBlueButton\BigBlueButton->sendRequest() (line 594 of /www/wwwroot/lms/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php).
If I use InsertDocumentParameters No error will be reported, but the default presentation will still be displayed.
I am confused whether there is a problem with my code. Could you give me an example of uploading a presentation?

**Comment by YouAreALegend** [comment]
I found that after calling the addPresentation function, bigbloebutton will report an error:
ERROR o.b.p.PresentationUrlDownloadService - IOException

**Comment by YouAreALegend** [comment]
After waiting for two months, no one can give me a simple reply.😭

**Comment by GhaziTriki** [comment]
@YouAreALegend The community is welcome to provide a fix. For myself I did not have the chance to work on this feature.

**Comment by YouAreALegend** [comment]
There are no issues with the interface. It's because the lxc I'm using cannot download remote files.Thank you for providing great convenience with the PHP API.
