### ISSUE TITLE
passing null to trim() is deprecated in php8

### ISSUE THREAD

**Issue by SandraLin1** [bigbluebutton/bigbluebutton-api-php#202]
Hi guys, 

I luckily updated to version 2.2 and I'm running into some issues, the error code is:

bigbluebutton/bigbluebutton-api-php/src/Parameters/CreateMeetingParameters.php:1541</small>
<br /><b>trim(): Passing null to parameter #1 ($string) of type string is deprecated: </b>

Looking into the code it's 
'bannerText'                             => trim($this->bannerText),

in line 1541. I didn't use the bannerText, so it should be null. Apparently, Php8 doesn't accept null in the trim-function.

Thanks for help

**Comment by GhaziTriki** [comment]
We were just discussing in team about removing default values and replacing them by null as default, it means if it is null the variable will not be sent in the HTTP request. Expect an update very soon.

**Comment by GhaziTriki** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton-api-php/pull/203

**Comment by jpxd** [comment]
Thanks for fixing this issue! Is there any ETA on when a new release can be published wich contains the fix? The most current released version (2.2.0) still contains the bug. Thanks for your work!
