### ISSUE TITLE
Api for webhooks not working with default settings

### ISSUE THREAD

**Issue by lesha724** [bigbluebutton/bigbluebutton-api-php#208]
Webhooks server validate checksum using only [sha1](https://github.com/bigbluebutton/bbb-webhooks/issues/30) and default hash algorithm is [sha256](https://github.com/bigbluebutton/bigbluebutton-api-php/blob/4d731c27cc34252f0a39c768c99415862ebb5329/src/BigBlueButton.php#L87C35-L87C60)

**Comment by andrekutianski** [comment]
Can you try to [set hash algorithm](https://github.com/bigbluebutton/bigbluebutton-api-php/blob/1434c046680d83d824318f076f22cdf67559b303/src/BigBlueButton.php#L92C12-L92C12) before making your call 

```php
$bbb = new BigBlueButton('url', 'secret');
$bbb->setHashingAlgorithm('sha1');
// webhook call...
```

**Comment by GhaziTriki** [comment]
Correct repl from @andrekutianski, confirmed on production products until bbb-webhhoks can handle more hash algorithms.
