### ISSUE TITLE
Correct Php-Version in '.scrutinizer.yml'?

### ISSUE THREAD

**Issue by DigitalTimK** [bigbluebutton/bigbluebutton-api-php#214]
I am not an expert in scrutinizer, but I saw that the environment has defined `php 8.1` in `.scrutinizer.yml`. Since the current min-version of the `bigbluebutton-api-php` is `php 7.4` (acc. to composer.json), wouldn't it be better to have scrutinizer changed to `php 7.4` too?

**Comment by GhaziTriki** [comment]
@DigitalTimK I am all with you. While PHP 7.4 is the minimum we should remove supporting prior versions https://www.php.net/supported-versions.php. We can keep PHP 7.4 as minimum version for a while.

**Comment by DigitalTimK** [comment]
Hello @GhaziTriki,

I like to come back to the previous observed problem:
- local computer runs php8.1
- in `composer.json` the minimum php is defined with `require.php: ">=7.4"`
- executing `composer require tracy/tracy --dev` installs Tracy v2.10 (but this version is not compatible to php7.4)
- scrutinizer did not recognize this as a problem
- risk of installation of other incompatible dependencies with every `composer update`

In order to avoid the installation of incompatible dependencies, I propose to add this into `composer.json`:
```
"config": {
  "platform": {
    "php": "7.4"
  }
},
```
See [documentation](https://getcomposer.org/doc/06-config.md#platform) that describes exactly this use case.

What do you think?

**Comment by GhaziTriki** [comment]
Hi @DigitalTimK 

I don't think it is really an issue. I shared how composer handles dependencies install here `https://github.com/bigbluebutton/bigbluebutton-api-php/pull/217#issuecomment-1951436837`

Did I understand you well?
