### ISSUE TITLE
Join as user

### ISSUE THREAD

**Issue by AamirAnwar3311** [bigbluebutton/bigbluebutton-api-php#219]
Is there any possibility to join as user. So that, the user cannot have access to end meeting. The user can only join the meeting as a student, not the teacher. Only the person who has created the meeting will be able to end the session or meeting. 

Please let me know. If there is any kind of possibility.

**Comment by GhaziTriki** [comment]
Hello,

Just use the `VIEWER` role at join. Kindly check the API docs

https://docs.bigbluebutton.org/development/api/#join

**Comment by AamirAnwar3311** [comment]
i am using the same PHP package for working. Can you please explain me in detail.

I am using this code for joining. 

$bbb = new BigBlueButton();

$joinMeetingParams = new JoinMeetingParameters($meetingID, $name, $password);
$joinMeetingParams->setRedirect(true);
$url = $bbb->getJoinMeetingURL($joinMeetingParams);

Thanks for your time.
