### ISSUE TITLE
[3.0/2.2][DEPRECATION] use lockSettingsDisableNotes instead of lockSettingsDisableNote'

### ISSUE THREAD

**Issue by RikiTikiTawi116** [bigbluebutton/bigbluebutton-api-php#229]
BIGBLUEBUTTON_RELEASE=3.0.0-alpha.5
bigbluebutton/bigbluebutton-api-php: 2.2.0
Drupal 10.2.5

In /var/log/bigbluebutton/bbb-web.log 'WARN  o.b.api.ParamsProcessorUtil - [DEPRECATION] use lockSettingsDisableNotes instead of lockSettingsDisableNote'

I use lockSettingsDisableNotes on Drupal side but any way I have this warning

**Comment by RikiTikiTawi116** [comment]
@GhaziTriki
U can found this param in create meeting parameters class.
All used versions is in first message.
And I have warning in bbb logs.
So, or api use old parameter name or it's bigbluebutton bug.

**Comment by GhaziTriki** [comment]
@RikiTikiTawi116 I mean can you ouptut the debug logs of your CreateMeetingParameters? You can use Tracy Debugger as example.

**Comment by RikiTikiTawi116** [comment]
@GhaziTriki its debuging, code & logs if I set parameter from api lib and without.
![image](https://github.com/bigbluebutton/bigbluebutton-api-php/assets/47721054/5fb8652d-d808-46f1-a3ae-30a73f05601b)
![image](https://github.com/bigbluebutton/bigbluebutton-api-php/assets/47721054/b29c1806-dc38-4ecf-a756-1ad4b93022a1)
![image](https://github.com/bigbluebutton/bigbluebutton-api-php/assets/47721054/f9a2c7df-c7df-430b-9615-2f11cf00746d)

![image](https://github.com/bigbluebutton/bigbluebutton-api-php/assets/47721054/c7176cf1-72e3-4b63-b8d4-e93ac33f9a5e)
![image](https://github.com/bigbluebutton/bigbluebutton-api-php/assets/47721054/a5b0aa74-f1c1-45af-a0f8-a15bb29d1d97)
![image](https://github.com/bigbluebutton/bigbluebutton-api-php/assets/47721054/a7f8bb08-e8a6-4793-a745-7bb57d7ad155)

**Comment by GhaziTriki** [comment]
@RikiTikiTawi116 Can you try `true` with small letters?

**Comment by RikiTikiTawi116** [comment]
![image](https://github.com/bigbluebutton/bigbluebutton-api-php/assets/47721054/4a76857f-0782-4e25-8f29-35bb3f3d6783)
![image](https://github.com/bigbluebutton/bigbluebutton-api-php/assets/47721054/4def5027-7d32-480a-a9f9-0e6084d96888)
![image](https://github.com/bigbluebutton/bigbluebutton-api-php/assets/47721054/1074dd7f-9e09-4d4c-b001-da8198ef88ee)
Thank you for suggestion! Unfortunately this change doesn't seems to resolve this issue. Moreover, this warning appears even if you do not use lockSettingsDisableNotes parameter.

**Comment by GhaziTriki** [comment]
@RikiTikiTawi116 Can you please try with the `dev-develop` from your composer?
