### ISSUE TITLE
url_encode

### ISSUE THREAD

**Issue by geezot** [bigbluebutton/bigbluebutton-api-php#23]
Hello
There is a mistake on line 450 in the file CreateMeetingParameters in the method getPresentationsAsXML
there is a urlencode I know this function is use for special caracters but on the server side there is no urldecode and you can't upload file because you have a message : Malformed URL in BBB log.
If you remove the urlencode everything work fine

Thanks :-) 
Fabrice

**Comment by ffdixon** [comment]
Thanks for reporting this ... we'll take a closer look.

**Comment by GhaziTriki** [comment]
@geezot can you please provide a file name that raises this error?

**Comment by geezot** [comment]
Hi @GhaziTriki 
All file name raises this error because all the url is encoded, I have described my method and the error in this issue : https://github.com/bigbluebutton/bigbluebutton-api-php/issues/21
the url_encode function replace all special chars by %nn and the bigbluebutton server receive a maformed url. 
2 solutions are possible : 
- Decode the url on bigbluebutton server
- remove the url_encode on the api (better solution I think)

sample message from web-bbb.log with the url_encode activated
![image](https://user-images.githubusercontent.com/4716847/40477282-56fff894-5f46-11e8-8d62-0d1a20aa09fd.png)
