### ISSUE TITLE
GetApiVersion Always return 2.2 version

### ISSUE THREAD

**Issue by RikiTikiTawi116** [bigbluebutton/bigbluebutton-api-php#230]
BIGBLUEBUTTON_RELEASE=3.0.0-alpha.5
bigbluebutton/bigbluebutton-api-php: 2.2.0
Drupal 10.2.5

$bbb = new BigBlueButton($base_bbb_url, $secret);
$bbb->getApiVersion();
Always return 2.0 version
SimpleXMLElement {#7486 ▼
  +"returncode": "SUCCESS"
  +"version": "2.0"
  +"apiVersion": "2.0"
  +"bbbVersion": SimpleXMLElement {#7499}
  +"graphqlWebsocketUrl": "wss://.../v1/graphql"
}

**Comment by GhaziTriki** [comment]
Hello @RikiTikiTawi116 this returned by BigBlueButton server. The PHP library is not involved.

I would recommend discussing this choice in the security forums : https://groups.google.com/g/bigbluebutton-dev

**Comment by RikiTikiTawi116** [comment]
@GhaziTriki
But in api library any sign for version. How bigbluebutton can know version of my api library?

**Comment by GhaziTriki** [comment]
BigBlueButton API and the library versions are decoupled. The library is compatible with new and old versions of BigBlueButton.

The library versioning is managed differently than BigBlueButton API version. Here some reading https://phptherightway.com/#composer_and_packagist
