### ISSUE TITLE
create meeting room parameters

### ISSUE THREAD

**Issue by Siba94** [bigbluebutton/bigbluebutton-api-php#27]
@ffdixon How can I use the customLogoURL option in creating meeting room API. As mentioned in BigBlueButton documentation there is no option for that.

**Comment by GhaziTriki** [comment]
@Siba94 
Introduced in `2.0.0` release of the API.

https://github.com/bigbluebutton/bigbluebutton-api-php/blob/2.0.0/src/Parameters/CreateMeetingParameters.php#L469

You need to use `$params->setLogo($logoURL);`
