### ISSUE TITLE
Fatal error: Uncaught RuntimeException: Unhandled curl error: Could not resolve host

### ISSUE THREAD

**Issue by clecioantao** [bigbluebutton/bigbluebutton-api-php#28]
Hi, I have this same problem in setting up the meeting. 

Fatal error: Uncaught RuntimeException: Unhandled curl error: Could not resolve host: api in /var/www/html/bbb-api/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:388 Stack trace: #0 /var/www/html/bbb-api/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(101): BigBlueButton\BigBlueButton->processXmlResponse('api/create?name...', '') #1 /var/www/html/bbb-api/create-meeting.php(29): BigBlueButton\BigBlueButton->createMeeting(Object(BigBlueButton\Parameters\CreateMeetingParameters)) #2 {main} thrown in /var/www/html/bbb-api/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 388

**Comment by aghfatehi** [comment]
reference from : https://groups.google.com/forum/#!msg/bigbluebutton-setup/iO8z2LeEq9M/DpGVgqK8CAAJ

/var/www/learning/vendor/bigbluebutton/bigbluebutton-api-php/src/Responses

In the file SetConfigXMLResponse.php correct the line:
public function getToken()
{
 return $this->rawXml->configToken->__toString();
}

 it was 'return $this->rawXml->Token->__toString();'

**Comment by clecioantao** [comment]
Hi. Thank you!
I made this change, but the error persists...
Below the file SetConfigXMLResponse.php

_namespace BigBlueButton\Responses;
class SetConfigXMLResponse extends BaseResponse
{
    /**
     * @return bool
     */
    public function getToken()
    {
        return $this->rawXml->Token->__toString();
    }
}_

And this is the example code I'm using, I needed to insert ... that was not in the original code and the variables as parameter:

<?php
require_once './vendor/autoload.php';
use BigBlueButton\BigBlueButton;
use BigBlueButton\Parameters\CreateMeetingParameters;

$meetingID = '1234';
$meetingName = 'clecio';
$attendee_password = '123';
$moderator_password = '321';
$duration = '0';
$urlLogout = '';
$isRecordingTrue = 'false';

$bbb = new BigBlueButton();

$createMeetingParams = new CreateMeetingParameters($meetingID, $meetingName);
$createMeetingParams->setAttendeePassword($attendee_password);
$createMeetingParams->setModeratorPassword($moderator_password);
$createMeetingParams->setDuration($duration);
$createMeetingParams->setLogoutUrl($urlLogout);
if ($isRecordingTrue) {
	$createMeetingParams->setRecord(true);
	$createMeetingParams->setAllowStartStopRecording(true);
	$createMeetingParams->setAutoStartRecording(true);
}

$response = $bbb->createMeeting($createMeetingParams);
if ($response->getReturnCode() == 'FAILED') {
	return 'Can\'t create room! please contact our administrator.';
} else {
	// process after room created
}

Regards.

**Comment by GhaziTriki** [comment]
@clecioantao Did you setup your environment variables `BBB_SECRET` and `BBB_SERVER_BASE_URL` ?

**Comment by clecioantao** [comment]
Yes, in the /etc/apache2/envvars

Em dom, 12 de ago de 2018 14:52, Ghazi Triki <notifications@github.com>
escreveu:

**Comment by GhaziTriki** [comment]
OK it seems like it well set-up.
Can you please try creating a room without setting a custom configXML and see if you still have this error?
By the way this error is purely PHP and not related to the library. Make sure you BigBlueButton IP is reachable by the library.

**Comment by GhaziTriki** [comment]
Sorry I mislead you.

The change suggested in the forum thread is wrong. A fixed version of `SetConfigXMLResponse` is available in the latest `dev-master`.

If you debug your `BigBlueButton` instance can you see `securitySecret`and `bbbServerBaseUrl` filled with the values your provided in your `envvars` file?

**Comment by clecioantao** [comment]
Hello all well?

I am declaring the variables in /etc/apache2/envvars:

export BBB_SECRET = '50d35e393342cde6dad0d65be00XXXXX'
export BBB_SERVER_BASE_URL = 'https://bbb.matizedigital.com.br/bigbluebutton/'

But it is not loading, see in PHP code:

`$ret1 = apache_getenv("SERVER_ADDR");
echo "Server Address " . $ret1 . "<br>";
$ret2 = apache_getenv("BBB_SECRET");
echo "VAR BBB_SECRET " . $ret2 . "<br>";
$ret3 = apache_getenv("BBB_SERVER_BASE_URL");
echo "VAR BBB_SERVER_BASE_URL " . $ret3 . "<br>";`

Return:

Server Address 192.168.33.11
VAR BBB_SECRET 
VAR BBB_SERVER_BASE_URL 

Fatal error: Uncaught RuntimeException: Unhandled curl error: Protocol " https" not supported or disabled in libcurl in /var/www/html/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:388 Stack trace: #0 /var/www/html/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(101): BigBlueButton\BigBlueButton->processXmlResponse(' https://bbb.ma...', '') #1 /var/www/html/bbb/create-meeting.php(38): BigBlueButton\BigBlueButton->createMeeting(Object(BigBlueButton\Parameters\CreateMeetingParameters)) #2 {main} thrown in /var/www/html/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 388

Any idea what might be going on?

Thanks!

**Comment by GhaziTriki** [comment]
Hi @clecioantao,

Please remove white-spaces surrounding the equals sign to look like the following:

```
export BBB_SECRET="50d35e393342cde6dad0d65be00XXXXX"
export BBB_SERVER_BASE_URL="bbb.matizedigital.com.br/bigbluebutton"
```

**Comment by clecioantao** [comment]
Now yes!

In addition to removing the space it is necessary to remove the "https: //"
Thank you very much @GhaziTriki !!!

Regards.

**Comment by GhaziTriki** [comment]
@clecioantao happy that works. Having http or https works fine with the API. Take a look here https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/.travis.yml#L24
And dont forget the trailing slash.

**Comment by nplesa** [comment]
Hi,

I have same issue about unhandled curl error: Could not resolve host: api", exception: "RuntimeException"..can you tell me what i have to do to solve this problem?

thanks,

**Comment by GhaziTriki** [comment]
@nplesa Did you read the previous comments and try to solve your issue?

**Comment by nplesa** [comment]
Yes, i tried removing https from BBB SERVER URL..

**Comment by nplesa** [comment]
But still i have the error.

**Comment by nplesa** [comment]
Thank you! Solved here!
With:
php artisan config:cache
php artisan config:clear
Respect!
