### ISSUE TITLE
Getting response code FAILED for getMeetingInfo

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [bigbluebutton/bigbluebutton-api-php#29]
I am trying to use credentials from **api-mate** and trying to create metting in localhost using Laravel framework, I am getting FAILED as response code for `getMeetingInfo` and meeting ID for `createMeeting` can you give some idea how I should proceed?

It is actually returning 404 error, that is what I got when I dumped `$data` in `processXmlResponse()` .

**Comment by GhaziTriki** [comment]
@PrafullaKumarSahu Any update?

**Comment by PrafullaKumarSahu** [comment]
Hello @GhaziTriki , thank you for your reply, I installed big blue button on my server and it worked. I am trying to configure everything as per my requirement, if I will face again some problem, I will definitely let you know.
