### ISSUE TITLE
Change Recording format

### ISSUE THREAD

**Issue by lilit1141** [bigbluebutton/bigbluebutton-api-php#35]
Is it possible convert BBB playback recordings to video format?

**Comment by ffdixon** [comment]
It's an open enhancement request for BigBlueButton.  Currently, our focus is on releasing an update to the HTML5 client.  We're working hard to move from Flash to pure HTML5.

Duplicate: https://github.com/bigbluebutton/bigbluebutton/issues/1969

**Comment by lilit1141** [comment]
In documentation it is written that  **playback is handled by HTML, CSS and Javascript libraries; it is fully available in Mozilla Firefox and Google Chrome(also in Android devices).**

So how we can watch the recording?

Thank you!

**Comment by ffdixon** [comment]
Try creating a recording on our demo server at

 https://demo.bigbluebutton.org

and then you can view the recording link after the recording is processed.

![image](https://user-images.githubusercontent.com/290351/49591887-aa488200-f93d-11e8-8b79-f90dde1ae9fc.png)

**Comment by lilit1141** [comment]
Thank you!
