### ISSUE TITLE
How to make checksum?

### ISSUE THREAD

**Issue by DemianKost** [bigbluebutton/bigbluebutton-api-php#38]
Hi everybody!

I'm trying to create meeting with Laravel. And have problem with checksum, who can write here a small instruction how to make request to create meeting with Laravel?

**Comment by ffdixon** [comment]
We've not used Laravel before.  But here are the steps to create a valid checksum

  http://docs.bigbluebutton.org/dev/api.html#usage

**Comment by DemianKost** [comment]
Can you tell me more about it? Because I tried this method - but thisc doesn't work :(

**Comment by ffdixon** [comment]
Can you be more specific about what you tried (can you share sample code).   Without seeing what you are trying to do (i.e. sample code), it's hard to pinpoint the errors.

**Comment by DemianKost** [comment]
Here is part of my code to create meeting

`$checksum = sha1('name=Test&meetingID=123&attendeePW=111222&moderatorPW=333444');

        $res = $Client->post('https://myworldtoken.com/bigbluebutton/api/create?name=Test&meetingID=123&attendeePW=111222&moderatorPW=333444&checksum=' . $checksum);

        echo $res->getStatusCode();
        // "200"
        echo $res->getHeader('content-type')[0];
        // 'application/json; charset=utf8'
        echo $res->getBody();`

And this does'nt work, every time I get a error about FAILES checksum.

**Comment by aliraza170** [comment]
I wanted to updated the footer in greenlight-v3,
I am tired to find, Idon't find the files in greenlight directory by cloning it more ever I am using
` **docker exec -it greenlight-v3 /bin/bash**`
to edit the changes
