### ISSUE TITLE
Unhandled curl error: Connection timed out after 10001 milliseconds

### ISSUE THREAD

**Issue by guruprasad-ks-23** [bigbluebutton/bigbluebutton-api-php#40]
"message": "Unhandled curl error: Connection timed out after 10001 milliseconds",
"exception": "RuntimeException",
    "file": "/var/www/vhosts/cnjxnb/httpdocs/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php",
    "line": 389,
    "trace": [
        {
            "file": "/var/www/vhosts/cnjxnb/httpdocs/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php",
            "line": 102,
            "function": "processXmlResponse",
            "class": "BigBlueButton\\BigBlueButton",
            "type": "->"
        },

**Comment by GhaziTriki** [comment]
@guruprasad-ks-23 Your server seems to be unreachable. Can your script access to your server?

**Comment by GhaziTriki** [comment]
Closing this issue. The timeout happens when the server is unreachable.

**Comment by daptontdev1** [comment]
Any solution from anyone? I am facing the same issues.
