### ISSUE TITLE
How to integrate it with CodeIgniter.

### ISSUE THREAD

**Issue by IAmMukeshKumar** [bigbluebutton/bigbluebutton-api-php#42]
Hi Team,

Please give me some reference to integrate and use this fantastic API with codeIgniter.
I am not finding ways to do it.

**Comment by GhaziTriki** [comment]
Hello @IAmMukeshKumar ,
CodeIgniter uses composer, you just have to install this library as a normal composer dependency.

You will find more by reading the wiki page https://github.com/bigbluebutton/bigbluebutton-api-php/wiki/Installation
