### ISSUE TITLE
How to check if URL / Secret are right?

### ISSUE THREAD

**Issue by cahueya** [bigbluebutton/bigbluebutton-api-php#49]
Thank you for that very clear API!
I am in the process of developing a BBB management tool for a CMS and with the methods I am currently applying, if the user entered a wrong SECRET in the configurations, they will only receive an unspecific XML error on the attempt to create a meeting.

I would like to have a way of confirming the correctness of the URL/SECRET combination and I thought that the ApiVersionCheck call would do so, but it works when only the URL is working.

Which function would you use for the checkup of URL/SECRET if there are no meetings running on the server?

Thank you for suggestions!

**Comment by ffdixon** [comment]
You could do a [isMeetingRunning](http://docs.bigbluebutton.org/dev/api.html#ismeetingrunning) on a random string.  It would `<messageKey>checksumError</messageKey>` when the checksum test fails.

**Comment by cahueya** [comment]
Ok, so if the URL/Secret combo is correct but that meeting does not exist, would it return some other specific code to cling a condition to?

**Comment by cahueya** [comment]
I got it working, thank you! This issue can be closed!
