### ISSUE TITLE
How do you generate checksum on PHP?

### ISSUE THREAD

**Issue by besingamkb** [bigbluebutton/bigbluebutton-api-php#51]
I am integrating webhooks on my bbbserver but I cant create/register a webhook because of checksum error. how did you guys do it on your side? I follow this docs https://docs.bigbluebutton.org/dev/webhooks.html#hookscreate

**Comment by erenilhan** [comment]
$params => is your create paramaterrs.  


```
$queryBuild = http_build_query($params);
$checkSum = sha1($endpoint . $queryBuild . env('BBB_SECRET'));
$lastUrl = env('BBB_SERVER_BASE_URL') . 'api/join?' . $queryBuild . '&checksum=' . $checkSum;
```

**Comment by besingamkb** [comment]
@erenilhan what would be the value of `$endpoint`?

**Comment by erenilhan** [comment]
@besingamkb  
I created it directly using php api. that's why I shared that code.
but its like webhooks
For example;
http://yourserver.com/bigbluebutton/api/hooks/create?[parameters]&checksum=[checksum]
`$parameters=['callbackURL'=>'your call back url',
meetingId='your meeting Id', 
getRaw=>booelan]`

and after
sha1(callback url.data body.shared secret)

```
$queryBuild = http_build_query($parameters);
$checkSum = sha1($yourCallBackUrl . $queryBuild . $yourBBBSecretApiKey);

```

but i didn't test.

**Comment by besingamkb** [comment]
@erenilhan i still get `checksumError` please see my code below.

```php
    public function hookCreate($meetingId)
    {
        $callbackURL = route('eboard.join_meeting', $meetingId)
        $parameters = [
            'callbackURL' => $callbackURL,
            'meetingID' => $meetingId,
            'getRaw' => true
        ];

        $queryBuild = http_build_query($parameters);
        $checksum = sha1($callbackURL.$queryBuild.env('BBB_SECRET'));
        $url = env('BBB_SERVER_BASE_URL') . "api/hooks/create?" . $queryBuild . "?checksum=" . $checksum;
        
        // die and dump
        dd($url);
    }
```

**Comment by erenilhan** [comment]
@besingamkb 
 ```
   $callbackURL = route('eboard.join_meeting', $meetingId)
    $parameters = [
        'callbackURL' => $callbackURL,
        'meetingID' => 'random-2329449',
        'getRaw' => true
    ];
    $queryBuild = http_build_query($parameters);
    $checksum = sha1('hooks/list' . $queryBuild . env('BBB_SECRET'));
    $url = env('BBB_SERVER_BASE_URL') . "api/hooks/list?" . $queryBuild . "&checksum=" . $checksum;
    return response()->json($url);
```

    $checksum = sha1('hooks/list' . $queryBuild . env('BBB_SECRET'));

Can you replace sha1($callbackURL....)

 sha1('**hooks/list'**....)
also;

    **$url = env('BBB_SERVER_BASE_URL') . "api/hooks/list?" . $queryBuild . "&checksum=" .$checksum;**  
 "?checksum=...." **replace** "&checksum=...." 


I did check and everything is fine. Please test and reply.

**Comment by GhaziTriki** [comment]
Hello @erenilhan 

Currently we did not implement webhooks support to this library. But it is feature that we definitely need. Will give you an udpate soon.

**Comment by GhaziTriki** [comment]
@besingamkb & @erenilhan Webhooks are now implemented into the API. Could you please test the `dev-master` with composer and give use feedback?

**Comment by besingamkb** [comment]
@GhaziTriki thank you i'll check it it out

**Comment by besingamkb** [comment]
@GhaziTriki hi sorry i just got cameback to this issue. it seems it is not yet on the documentation. how can we use hook using this api? can you give me some code example

**Comment by GhaziTriki** [comment]
For creating a webhook you just do

```php
$callBackUrl = 'https://bbb.website.com/hook/catcher';
$bbb->hooksCreate(new HooksCreateParameters($callBackUrl)
```

**Comment by besingamkb** [comment]
thank you so much.
