### ISSUE TITLE
creating hooks but it didn't fire any events

### ISSUE THREAD

**Issue by besingamkb** [bigbluebutton/bigbluebutton-api-php#52]
Hi @GhaziTriki I have created a hooks but it seems to be not working. 

```php
$hookParameter = new HooksCreateParameters("https://enw3jpw6d9p7b.x.pipedream.net");
    $hookParameter->setMeetingId($iMeetingId);
    $hookParameter->setGetRaw(true);
    $hookRes = $bbb->hooksCreate($hookParameter);
    Log::info($hookRes->getHookId());
```

below is the results when I try to list hook so it is registered.
```
BigBlueButton\Core\Hook::__set_state(array(
     'rawXml' => 
    SimpleXMLElement::__set_state(array(
       'hookID' => '2',
       'callbackURL' => $hookParameter = new HooksCreateParameters("https://enw3jpw6d9p7b.x.pipedream.net");
    $hookParameter->setMeetingId($iMeetingId);
    $hookParameter->setGetRaw(true);
    $hookRes = $bbb->hooksCreate($hookParameter);
    Log::info($hookRes->getHookId());
      SimpleXMLElement::__set_state(array(
      )),
       'meetingID' => 
      SimpleXMLElement::__set_state(array(
      )),
       'permanentHook' => 'false',
       'rawData' => '1',
    )),
     'hookId' => 2,
     'meetingId' => 'b4991f917a36b8d9c9666a8087d23f44ab0536f7-1578487391601',
     'callbackUrl' => 'https://enw3jpw6d9p7b.x.pipedream.net',
     'permanentHook' => false,
     'rawData' => false,
  )),

```

maybe a firewall something? or a configuration on my bbb server?

**Comment by GhaziTriki** [comment]
@besingamkb There currently an open issue with `getRaw` https://github.com/bigbluebutton/bigbluebutton/issues/8437

**Comment by besingamkb** [comment]
@GhaziTriki so I tried what you share on my previous issue.

```php
$hookParameter = new HooksCreateParameters("https://enw3jpw6d9p7b.x.pipedream.net");
//    $hookParameter->setMeetingId($iMeetingId);
//    $hookParameter->setGetRaw(true);
    $hookRes = $bbb->hooksCreate($hookParameter);
    Log::info($hookRes->getHookId());
```

so when I try to end a meeting.. it should fire an event right? but still i dont get any http request

**Comment by GhaziTriki** [comment]
Did you try catching webhooks with https://webhook.site? It did work for me.

**Comment by Cyb0org** [comment]
@besingamkb Have you installed bbb-webhooks on the BBB server side?
https://docs.bigbluebutton.org/dev/webhooks.html#installation
Don't forget to "bbb-conf --restart".
Webhooks works for me.

**Comment by richp10** [comment]
@besingamkb  - did you find a solution to this - I have the same problem

**Comment by besingamkb** [comment]
@richp10 not yet. i end up using `endCallbackUrl`

**Comment by rohitcoder** [comment]
Hey Guys, i just tried this and its working, simply  do ``sudo apt-get install bbb-webhooks`` and then register a webhook with 
```php
<?php 
use BigBlueButton\BigBlueButton; 
use BigBlueButton\Parameters\HooksCreateParameters; 
$bbb = new BigBlueButton();
$hookParameter = new HooksCreateParameters("https://enu288932k0yl.x.pipedream.net/");
$hookRes = $bbb->hooksCreate($hookParameter);
print_R($hookRes);
```
and it works for me!

**Comment by thrillsam** [comment]
Hi Guys, I am also facing the same problem. callback works through postman, curl command. but bbb-webhook emitter returns  **error in the callback call to** . Mine is Rails application. can you please any one help me on that

**Comment by GhaziTriki** [comment]
If you install the webhooks package in your server it will work.
