### ISSUE TITLE
Setting up a timed interview

### ISSUE THREAD

**Issue by emresaracoglu** [bigbluebutton/bigbluebutton-api-php#53]
Hello,

Thank you for this great project!

Is it possible to determine the duration of a conversation created?
For example, it is desired to create a 60-minute interview. Redirect to custom page after 60 minutes.

**Comment by GhaziTriki** [comment]
Hello @emresaracoglu 

Yes you can use `$createMeetingParams->setDuration(60)`. The duration is in minutes. You can check the `duration` parameter in the docs https://docs.bigbluebutton.org/dev/api.html#create.

**Comment by emresaracoglu** [comment]
Thank you!
