### ISSUE TITLE
Pre-upload slides

### ISSUE THREAD

**Issue by besingamkb** [bigbluebutton/bigbluebutton-api-php#55]
do we have this feature on our create API? 

https://docs.bigbluebutton.org/dev/api.html#pre-upload-slides

**Comment by GhaziTriki** [comment]
Hello @besingamkb 

Yes this feature is implemented in the PHP API client. You can find a sample code in the tests https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/tests/BigBlueButtonTest.php#L101-L157

**Comment by besingamkb** [comment]
thank you @GhaziTriki i'll try this.

**Comment by GhaziTriki** [comment]
@besingamkb Does it work for you now?

**Comment by besingamkb** [comment]
yeah. it works thanks @GhaziTriki
