### ISSUE TITLE
change meetings config

### ISSUE THREAD

**Issue by kosar501** [bigbluebutton/bigbluebutton-api-php#57]
After I Create Meeting...I want to dynamically change some of its config like disable desktop sharing.
based on bigbluebutton document I wrote below code which 
I get default config 
change it 
then I set it using setConfig function ... 
it successfully done and returned token which I used it to get join url...but when I go to the url and directed to the Conference nothing changed...
![Screenshot_15](https://user-images.githubusercontent.com/52377199/73835346-7c511d00-4822-11ea-85c4-0f66d567f782.png)
setConfig response
![Screenshot_16](https://user-images.githubusercontent.com/52377199/73835430-a0acf980-4822-11ea-8ed0-e060a1cfaf89.png)

**Comment by ffdixon** [comment]
The `setConfgXML` was only for the Flash client, and the BigBlueButton project has moved on to the HTML5 client.

Flash is EOL at the end of this year, and is already disappearing from the browsers (the next version of Safari will not have Flash).  

So we would recommend not doing any development with the Flash client.   There isn't an equivalent `setConfgXML` for the HTML5 client, but there is options to customize the client http://docs.bigbluebutton.org/2.2/customize.html.

**Comment by kosar501** [comment]
Thank you so much
