### ISSUE TITLE
currently unable to handle this request.

### ISSUE THREAD

**Issue by rogercong** [bigbluebutton/bigbluebutton-api-php#61]
Dear all,

Sorry to bother you!  I am a newbie to this.  Anyway, I tried to use this bigbluebutton-api-php, however, i am running into this problem for the past couple of days.  Following the instructions on github, I have created a composer project.  When I use it as:

<?php
require_once './vendor/autoload.php';
$bbb = new BigBlueButton();
$meetingId = $_POST['meeting'];
echo "welcome to $meetingId!";

I got this error message.  "This page isn't working, currently unable to handle this request."

Can someone tell me what problem do i have here?

Thank you in advance!
roger

**Comment by GhaziTriki** [comment]
@rogercong You did not finish describing your issue. Can you please update it?

**Comment by rogercong** [comment]
As mentioned in my message, if a person has signed in a conference and went to public chatting, for example, it's very easy for people to press 'back' button, instead of public chat icon.  My question is if it's possible to pop-up a confirm message box for people pressed 'back' button.  This is happening quite often when user use mobile.

**Comment by GhaziTriki** [comment]
@rogercong Please start with the wiki https://github.com/bigbluebutton/bigbluebutton-api-php/wiki and tell us if it works. Thanks you !
