### ISSUE TITLE
404 Not Found - Add Presentation

### ISSUE THREAD

**Issue by ghost** [bigbluebutton/bigbluebutton-api-php#63]
Hello, I Used BigBlueButton PHP API for about 1 Month and everything almost Ok
but tonight I tried to create a meeting and my website shows error
After that, I understood that in backend, API recieved 404 - Not Found Error
finnally I Commented below codes and Website work almost correctly
`if (!empty($payload)) {`
               ` //curl_setopt($ch, CURLOPT_HEADER, 0);`
             `   //curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');`
               ` curl_setopt($ch, CURLOPT_POST, 1);`
               ` curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);`
              `  /*curl_setopt($ch, CURLOPT_HTTPHEADER, [`
                  `  'Content-type: ' . $contentType,`
                   ` 'Content-length: ' . mb_strlen($payload),`
               ` ]);*/`
           ` }`
but presentasion slide not showing
can I solve this Problem?

**Comment by ffdixon** [comment]
> but presentasion slide not showing

Check the Javascript console and network tab in the developer tools for Chrome for errors.

**Comment by pouyaaofficial** [comment]
> > but presentasion slide not showing
> 
> Check the Javascript console and network tab in the developer tools for Chrome for errors.

after join in the meeting?

**Comment by pouyaaofficial** [comment]
[Log.log](https://github.com/bigbluebutton/bigbluebutton-api-php/files/4334064/Log.log)
Console Log file Attached to this Answer
in Network Console, there isn't my presentation
All of the Problems are from commenting these codes:
`'Content-type: ' . $contentType,`
`'Content-length: ' . mb_strlen($payload),`
The error was Suddenly, and before it BBB Works Correctly
But Error 404 - Not Found Troubles My Work

**Comment by GhaziTriki** [comment]
@pouyaaofficial Did you fix the issue?

The code below is mandatory to make the pre-uploaded documents work.

```php
'Content-type: ' . $contentType,
'Content-length: ' . mb_strlen($payload),
```

Your error might come from the code executing the library. Are you forwarding the HTTP call to the library?

**Comment by sazanof** [comment]
join the problem!
404 error when loading the default presentation or any other presentation. The problem is observed in the flash client. everything works fine in html5
![image](https://user-images.githubusercontent.com/3595562/82925148-05cd5c00-9f86-11ea-80fe-ac780de636a6.png)
