### ISSUE TITLE
Instance of BBB used on test has wrong version

### ISSUE THREAD

**Issue by Yurujai** [bigbluebutton/bigbluebutton-api-php#69]
Hi @GhaziTriki 

I was trying to fix test errors. See: https://github.com/bigbluebutton/bigbluebutton-api-php/pull/68

But when i'm trying to fix errors on statusCode responses I see that the instance of BBB that is used on test has a wrong version [1] ( testAPIVersion is broken, expected 2.0.0 and returned 0.9 )

Now, I dont know if its better to fix these test errors or if you can upgrade BBB instance using on test.

Feel free to close the issue if I'm wrong.

Thank you in advance!

[1] https://test-install.blindsidenetworks.com/bigbluebutton/api/

**Comment by GhaziTriki** [comment]
@Yurujai Thank you. We are discussing about how to make tests fixed, including this version.
