### ISSUE TITLE
joinMeeting error

### ISSUE THREAD

**Issue by royjr** [bigbluebutton/bigbluebutton-api-php#70]
getJoinMeetingURL works great but joinMeeting throws a fatal error
php 7.3

```
$joinMeetingParameters = new JoinMeetingParameters('','','');
$joinMeetingParameters->setMeetingId('test');
$joinMeetingParameters->setUsername('test');
$joinMeetingParameters->setPassword('test');
$joinMeetingParameters->setJoinViaHtml5(true);
$joinMeetingParameters->setRedirect(false);

$bbb = new BigBlueButton();
$response = $bbb->joinMeeting($joinMeetingParameters);
```

```
Warning: SimpleXMLElement::__construct(): Entity: line 6: parser error : Specification mandate value for attribute async in /vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490 
```
```
Warning: SimpleXMLElement::__construct(): in /vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490
```
```
Warning: SimpleXMLElement::__construct(): ^ in /vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490
```
```
Fatal error: Uncaught Exception: String could not be parsed as XML in /vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:490 Stack trace: #0 /vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(490): SimpleXMLElement->__construct('\nprocessXmlResponse('https://server') #2 /getjoinmeetingurl.php(20): BigBlueButton\BigBlueButton->joinMeeting(Object(BigBlueButton\Parameters\JoinMeetingParameters)) #3 {main} thrown in /vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490
```

**Comment by GhaziTriki** [comment]
@royjr If you execute the request in the browser you will see that it will not returning the XML result. Might be error 404 or 503. Could you check that please?

**Comment by hananaq** [comment]
im having the same issue, when i run the joinMeeting i get a set of errors, im running on php 7.1

Severity: Warning
Message: SimpleXMLElement::__construct(): Entity: line 37: parser error : Opening and ending tag mismatch: meta line 13 and head

Severity: Warning
Message: SimpleXMLElement::__construct(): </head>

Type: Exception
Message: String could not be parsed as XML


any way of fixing this ??

**Comment by sherkhanz** [comment]
Same here, the Join Meeting Url built by `getJoinMeetingUrl()` returns the index page when queries through `joinMeeting()` method. I simply dumped the data returned from curl before returning it as `SimpleXMLElement` and it was the BBB's default index page with 200 status code

**Comment by sherkhanz** [comment]
Okay found out that the issue was because i had `redirect` joinMeetingParameter set to true. Setting it to false returns joinMeetingResponse Object.
