### ISSUE TITLE
Error "Node no longer exists" when calling getParticipants() in a Meeting

### ISSUE THREAD

**Issue by davidrojo** [bigbluebutton/bigbluebutton-api-php#71]
When calling `getParticipants()` of a meeting, there is an error in `Attendee` constructor because `$xml->customdata->children()` fails if `customdata` doesn't exists.

`Warning: BigBlueButton\Core\Attendee::__construct(): Node no longer exists`

**Comment by GhaziTriki** [comment]
@davidrojo Thank you for finding this.

The customdata might exist

https://github.com/bigbluebutton/bigbluebutton/blob/41f19a2cd1bc7dae76cbd805cdc3ddfbf1e6ab18/bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/get-meeting-info.ftlx#L39-L45

I think the check you put is good.

**Comment by GhaziTriki** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton-api-php/commit/e9624dfa2a59c26dbcc867763d8b3e9192ec871e
