### ISSUE TITLE
Set presenter for attendee per API call

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/bigbluebutton-api-php#74]
Hi,

I use bigbluebutton for a lot lightningtalks. We will have many participants. 
I want to have the workflow that only the one who is giving a talk gets "presenter" manually, but didn't want to search that one in a large list.

I got the idea to use a list of names and an external program to enable this option. The current API seems not be able to archieve this. 

That may need "room id", "user name", "verify user in room", "get presenter status", "set presenter" 

Any idea how that can be done?

regards
Reimar

**Comment by GhaziTriki** [comment]
@ReimarBauer Hello,

Thank you for posting this request. Could you please give more details?

However I think you post should go to https://groups.google.com/forum/#!forum/bigbluebutton-users as you are exposing a usability request. Did I understand you well?

**Comment by ReimarBauer** [comment]
@GhaziTriki I continue there. Just a note. On a larger list of attendees it is difficult to set presenter to someone. If you have the names beforehand, which is the case on sessions, than you have to match only times with names and can send a request by an addtional tool.

**Comment by ReimarBauer** [comment]
Thx for implementing.
