### ISSUE TITLE
The meeting ID that you supplied did not match any existing meetings

### ISSUE THREAD

**Issue by temirikov** [bigbluebutton/bigbluebutton-api-php#77]
Step by step:
1) i create the meeting
2) join as moderator
3) join some users as attendees
3) end meeting using button in HTML5 client, or using API - doesnt matter

After that i create this meeting one more time without any error
The try to join and this kind of error appears: The meeting ID that you supplied did not match any existing meetings "key":"invalidMeetingIdentifier"

Nothing like this I do not get:
This conference was already in existence and may currently be in progress.

**Comment by haviduck** [comment]
use the setmeetingid to your createmeetingparams

**Comment by GhaziTriki** [comment]
I don't think this is an issue with the PHP library. You need to set the meeting ID every time you create it http://docs.bigbluebutton.org/dev/api.html#create
