### ISSUE TITLE
Guest parameter on Join?

### ISSUE THREAD

**Issue by royjr** [bigbluebutton/bigbluebutton-api-php#80]
This API is great, but why is it missing a simple "guest" parameter for joining meetings?
https://docs.bigbluebutton.org/dev/api.html#join

I'd like to use this to mark guests with the "moderator approval" settings using guestPolicy since most of our attendees are guests at the moment.

**Comment by dummyproj007** [comment]
Hi any one has idea how to set "moderator approval" settings for creating meeting in php code

**Comment by Yurujai** [comment]
Hi @dummyproj007 this PR allows create meetings with guestPolicy (https://github.com/bigbluebutton/bigbluebutton-api-php/pull/67). We are using these changes.

**Comment by dummyproj007** [comment]
i tried to add guestPolicy but it gives error, any sample code @Yurujai

**Comment by dummyproj007** [comment]
$createMeetingParams = new CreateMeetingParameters($meetingId, $selectFromMeetingDataDet->meetingName);
                        $createMeetingParams->setAttendeePassword($selectFromMeetingDataDet->attendeePassword);
                        $createMeetingParams->setModeratorPassword($selectFromMeetingDataDet->moderatorPassword);
                        
                        $createMeetingParams->setRecord(true);

                        //$createMeetingParams->setRecord(true);
                        $createMeetingParams->setAllowStartStopRecording($selectFromMeetingDataDet->allowStartStopRecording);
                        $createMeetingParams->setAutoStartRecording($selectFromMeetingDataDet->autoStartRecording);
                        $createMeetingParams->setWelcomeMessage($selectFromMeetingDataDet->welcomeMessage);
                        

                        $createMeetingParams->setDuration($selectFromMeetingDataDet->duration);
                        $createMeetingParams->setlogoutUrl($selectFromMeetingDataDet->logoutUrl);
                        $createMeetingParams->setModeratorOnlyMessage($selectFromMeetingDataDet->moderatorOnlyMessage);
                        $createMeetingParams->setWebcamsOnlyForModerator($selectFromMeetingDataDet->webcamsOnlyForModerator);
                        
                        $createMeetingParams->guestPolicy("ASK_MODERATOR");
                        //setMethodAllowsGuests
                        // $createMeetingParams->setAutoStartRecording($selectFromMeetingDataDet->allowStartStopRecording);

                        $response = $bbb->createMeeting($createMeetingParams);

**Comment by Yurujai** [comment]
The PR created 3 methods to set guestPolicy.

1. setModerateJoin()
2. setOpenJoin()
3. setBlockedJoin()

On your example you should use the 1st option, its an abstraction of multiple values that you have to control the guestPolicy, with this methods you dont need to know the values of BBB to set it.

**Comment by dummyproj007** [comment]
getting this error:
Call to undefined method BigBlueButton\Parameters\CreateMeetingParameters::setModerateJoin()
--
exception | Symfony\Component\Debug\Exception\FatalThrowableError

**Comment by Yurujai** [comment]
> ## getting this error:
> Call to undefined method BigBlueButton\Parameters\CreateMeetingParameters::setModerateJoin()
> exception | Symfony\Component\Debug\Exception\FatalThrowableError

I think you are using the master branch or last tag of a BBB PHP API and the PR is open yet. 

To use it, you should create a fork an implement the changes of PR or wait for the PR.

I think people who are working on BBB PHP API are busy (the situation in the world is complicated
) and they are working hard to implements all solutions.

**Comment by GhaziTriki** [comment]
@Yurujai Thank you for your support. We are very busy to provide the best implementations we can all over!

**Comment by dummyproj007** [comment]
thanks a lot @Yurujai  . For your help in fixing my issue of moderator approval issue . i used this solution for my fixes
"this PR allows create meetings with guestPolicy (#67). We are using these changes."

**Comment by dummyproj007** [comment]
i am working on getrecordings with meeting id, but its not working . it gives all the recordings. not particular to meeting id.

--------------
        $recordingsParams = array(
            'meetingID' => '1587274606'//$request->meetingId,
        );
        $getRecordParams = new GetRecordingsParameters($recordingsParams);
        $response= $this->bbb->getRecordings($getRecordParams);
-------------
Anything wrong here.
Also do we have download option for this recordings?

**Comment by dummyproj007** [comment]
Hi Guys,

I am trying to use maxParticipants option
but its now happening . any suggestions

**Comment by Noext** [comment]
any update on the original issue ? 

it seem that we cannot generate link for a guest , JoinMeetingParameters has no guest property

**Comment by GhaziTriki** [comment]
Guest has been implemented in https://github.com/bigbluebutton/bigbluebutton-api-php/releases/tag/2.0.11
