### ISSUE TITLE
BBB PHP API Laravel Wrapper Issue ---getMeetingInfo always returns {}

### ISSUE THREAD

**Issue by TechLee2019** [bigbluebutton/bigbluebutton-api-php#88]
Hi,
I need to know if a meeting room is still available or no, so i have tried with isMeetingRunning api, but it fails, always return {}, so i moved to GetMeetingInfo Api, but same goes with this.

Any API related to meeting room information, always gives me {} response.
Here goes my codes in the followings.

$bbb = new BigBlueButton();
$meetingRunningParameters = new GetMeetingInfoParameters($meetingID, '', $moderator_password);
$meetStatus = $bbb->getMeetingInfo($meetingRunningParameters);

I am using PHP 7.44, Laravel Framework 5.58

**Comment by Yurujai** [comment]
On the wiki example for GetMeetingInfoParameters [1] it has a wrong number of variables on the constructor [2].

You can try this to get info ( just remove your 2nd variable ):

`$meetingRunningParameters = new GetMeetingInfoParameters($meetingID, $moderator_password);`

[1] https://github.com/bigbluebutton/bigbluebutton-api-php/wiki/API-Get-Meeting-Info
[2] https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/src/Parameters/GetMeetingInfoParameters.php#L43

**Comment by Yurujai** [comment]
I created a new issue for the documentation.

See: https://github.com/bigbluebutton/bigbluebutton-api-php/issues/89

**Comment by Happy-2020** [comment]
Yurujai,
Thanks for your advice.
Have tried with that 2 parameters, Because the php api parameters are having only 2.
It didn't work, so i checked on the wiki documents and follow the code.
