### ISSUE TITLE
[WIKI] Example of GetMeetingInfoParameters is wrong

### ISSUE THREAD

**Issue by Yurujai** [bigbluebutton/bigbluebutton-api-php#89]
The page of GetMeetingInfoParameters example is wrong [1].

In the example uses 3 variables on the constructor but the constructor have only 2.

See [2]

[1] https://github.com/bigbluebutton/bigbluebutton-api-php/wiki/API-Get-Meeting-Info
[2] https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/src/Parameters/GetMeetingInfoParameters.php#L43

**Comment by Happy-2020** [comment]
Yurujai,
Thanks for your advice.
Have tried with that 2 parameters, Because the php api parameters are having only 2.
It didn't work, so i checked on the wiki documents and follow the code.

**Comment by Happy-2020** [comment]
Still its giving me {} response only. I checked this community, and found a comment saying.. execute this command on the server, bbb-conf --clean, bbb-conf -- check...
But unfortunately, i am still getting the same response {}, Do I have to touch some configuration files? Please kindly refer my issue, and give me your advice.

Thanks.

**Comment by Happy-2020** [comment]
//-------CODE FOR CREATING MEETING ROOM---------
$meetingID = $meetID;
$meetingName = $meetName;
$attendee_password = 'zxcewef';
$moderator_password = 'ddwqas';
$duration = 60*1000*60;

$urlLogout = url('/')."xxx";
$isRecordingTrue = true;

$createMeetingParams = new CreateMeetingParameters($meetingID, $meetingName);        $createMeetingParams->setAttendeePassword($attendee_password);
$createMeetingParams->setModeratorPassword($moderator_password);
$createMeetingParams->setDuration($duration);
$createMeetingParams->setLogoutUrl($urlLogout);
if ($isRecordingTrue) {
     $createMeetingParams->setRecord(true);
     $createMeetingParams->setAllowStartStopRecording(true);
     $createMeetingParams->setAutoStartRecording(true);
}
        
$response = $bbb->createMeeting($createMeetingParams);

**Comment by Happy-2020** [comment]
//--------CODE FOR CHECKING ROOMINFOR---------------
$bbb = new BigBlueButton();
$meetingRunningParameters = new GetMeetingInfoParameters($meetingID, $moderator_password);
$meetStatus = $bbb->getMeetingInfo($meetingRunningParameters);

**Comment by GhaziTriki** [comment]
Thank you fixed.

**Comment by Beginner95** [comment]
> //--------CODE FOR CHECKING ROOMINFOR---------------
> $bbb = new BigBlueButton();
> $meetingRunningParameters = new GetMeetingInfoParameters($meetingID, $moderator_password);
> $meetStatus = $bbb->getMeetingInfo($meetingRunningParameters);

I also receive a message
```
GetMeetingInfoResponse {#1546 ▼
  -meeting: null
  #rawXml: SimpleXMLElement {#1545 ▼
    +"returncode": "FAILED"
    +"messageKey": "notFound"
    +"message": "We could not find a meeting with that meeting ID"
  }
}
```
Did you solve the problem?
