### ISSUE TITLE
Comment in getRecordingsWithXmlResponseArray() of the class BigBlueButton

### ISSUE THREAD

**Issue by lazarait** [bigbluebutton/bigbluebutton-api-php#9]
Hi!
I think that there is a problem concerning the comment on the method getRecordingsWithXmlResponseArray() of the class BigBlueButton. Indeed, it said that it requires an array
 "/* USAGE:
        $recordingParams = array(
            'meetingId' => '1234',		-- OPTIONAL - comma separate if multiple ids
        );"
However the method expects an input "$recordingParams" of type "GetRecordingsParameters" because the method "getHTTPQuery()" of the latter class is called in the line 203.
Sincerly yours

**Comment by GhaziTriki** [comment]
The last time you were using the library ```getRecordings``` API was not impltemented to this library. Now it has been implemented, the method ```getRecordingsWithXmlResponseArray```does no more exist as it comes from the old version.
