### ISSUE TITLE
GetMeetingInfo, IsMeetingRunning API always returns {} whether its running or not.

### ISSUE THREAD

**Issue by TechLee2019** [bigbluebutton/bigbluebutton-api-php#90]
Hi,
I am using PHP 7.44, Laravel Framework 5.58
I need to know if a meeting room is still available or no, so i have tried with isMeetingRunning api, but it fails, always return {}, so i moved to GetMeetingInfo Api, but same goes with this.

Still its giving me {} response only. I checked this community, and found a comment saying.. execute this command on the server, bbb-conf --clean, bbb-conf -- check...
But unfortunately, i am still getting the same response {}, Do I have to touch some configuration files? Please kindly refer my issue, and give me your advice.

//-------CODE FOR CREATING MEETING ROOM---------
$meetingID = $meetID;
$meetingName = $meetName;
$attendee_password = 'zxcewef';
$moderator_password = 'ddwqas';
$duration = 60 * 1000 * 60;

$urlLogout = url('/')."xxx";
$isRecordingTrue = true;

$createMeetingParams = new CreateMeetingParameters($meetingID, $meetingName); $createMeetingParams->setAttendeePassword($attendee_password);
$createMeetingParams->setModeratorPassword($moderator_password);
$createMeetingParams->setDuration($duration);
$createMeetingParams->setLogoutUrl($urlLogout);
if ($isRecordingTrue) {
$createMeetingParams->setRecord(true);
$createMeetingParams->setAllowStartStopRecording(true);
$createMeetingParams->setAutoStartRecording(true);
}

$response = $bbb->createMeeting($createMeetingParams);

//--------CODE FOR CHECKING ROOMINFOR---------------
$bbb = new BigBlueButton();
$meetingRunningParameters = new GetMeetingInfoParameters($meetingID, $moderator_password);
$meetStatus = $bbb->getMeetingInfo($meetingRunningParameters);

Can anyone pls give me your experiences and advice.
Thanks!

**Comment by GhaziTriki** [comment]
A new non standard API function has been added to check the meeting states in `isMeetnigRunning` is confusing. This function is `isMeetingExisting`.
