### ISSUE TITLE
String could not be parsed as XML

### ISSUE THREAD

**Issue by alimashalkpu** [bigbluebutton/bigbluebutton-api-php#91]
got this error while working in laravel 6 for getting all meeting, and check inside BigBlueButton class response from api is correct just new SimpleXMLElement($data); is not working properly. I am working with windows 10 xammp

"SimpleXMLElement::__construct(): Entity: line 6: parser error : Opening and ending tag mismatch: hr line 5 and body"

**Comment by shingtacs** [comment]
How did you solved this?
