### ISSUE TITLE
Could not resolve host: api

### ISSUE THREAD

**Issue by Entretoize** [bigbluebutton/bigbluebutton-api-php#95]
Hello; i'm following the wiki but at the first step after install I have errors.
I copied the code:

```
use BigBlueButton\BigBlueButton;
use BigBlueButton\Parameters\CreateMeetingParameters;

$bbb                 = new BigBlueButton();
$createMeetingParams = new CreateMeetingParameters('bbb-meeting-uid-65', 'BigBlueButton API Meeting');
$response            = $bbb->createMeeting($createMeetingParams);

echo "Created Meeting with ID: " . $response->getMeetingId();
```

And I have that error:

`Fatal error: Uncaught RuntimeException: Unhandled curl error: Could not resolve host: api in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:480 Stack trace: #0 /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(108): BigBlueButton\BigBlueButton->processXmlResponse('api/create?name...', '') #1 /var/www/bigbluebutton-default/test.php(14): BigBlueButton\BigBlueButton->createMeeting(Object(BigBlueButton\Parameters\CreateMeetingParameters)) #2 {main} thrown in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 480`

I didn't put the BBB_SECRET and BBB_SERVER_BASE_URL environnement variables yet because it's not said what is needed to be put in but it doesn't seem the problem comes from that.

Thanks

**Comment by GhaziTriki** [comment]
You need to have those values in the environment, else the "" (empty) host in unreachable.

**Comment by Entretoize** [comment]
OK, thank you but there's nothing in the wiki about those variables, what to put in ?

**Comment by Entretoize** [comment]
I found: http://docs.bigbluebutton.org/2.2/install.html#4--install-bigbluebutton
