### ISSUE TITLE
BBB with Laravel 6.

### ISSUE THREAD

**Issue by ripon52** [bigbluebutton/bigbluebutton-api-php#98]
I need your guideline about BBB integration with Laravel-6.

What i did yet ?
I installed fresh Laravel -6.
Installed https://packagist.org/packages/bigbluebutton/bigbluebutton-api-php

What's next now ?

**Comment by joisarjignesh** [comment]
use this package bbb integration in laravel  https://github.com/joisarjignesh/bigbluebutton

**Comment by ripon52** [comment]
How to get this two ?

BBB_SECURITY_SALT=bbb_secret_key   
BBB_SERVER_BASE_URL=https://example.com/bigbluebutton/

**Comment by toto4ds** [comment]
in .env 
or 
putenv("BBB_SERVER_BASE_URL=".$BBB_SERVER_BASE_URL);
putenv("BBB_SECRET=".$BBB_SECRET);

**Comment by joisarjignesh** [comment]
@ripon52 first u get security_salt and url from server 
run this command 

>  sudo bbb-conf --secret

if don't have bigblue server then create and install bbb [see](https://docs.bigbluebutton.org/2.2/install.html)

**Comment by ripon52** [comment]
Am using Ubuntu 18.04 . Whenever i tried to install bbb its saying , You should run this command at ubuntu 16.04. What to do ?

.
Is there easy way to install at Windows ?

**Comment by joisarjignesh** [comment]
use this script it will automatically install bigbluebutton on server https://github.com/bigbluebutton/bbb-install

**Comment by shingtacs** [comment]
> use this package bbb integration in laravel https://github.com/joisarjignesh/bigbluebutton

I already installed the above package and tried to check it using this:

dd(\Bigbluebutton::isConnect());
it returned false

I also tried installing this 
https://packagist.org/packages/bigbluebutton/bigbluebutton-api-php

the problem is that it always returned the error:

String could not be parsed as XML

I don't know what happened. I just follow the steps.

**Comment by djoudi** [comment]
https://github.com/djoudi/BBB-Laravel
